### ISSUE TITLE
Error when trying to use the app.

### ISSUE THREAD

**Issue by amiroo54** [parchlinuxB/namban#6]
Here is the log. 
```
amiroof@amiroofPC:~$ sudo namban

(python3:186128): Gtk-WARNING **: 09:28:17.940: Unable to acquire session bus: Error spawning command line “dbus-launch --autolaunch=70ddefbd4deb4e3bbb83062a7a808f78 --binary-syntax --close-stderr”: Child process exited with code 1
cp: cannot create regular file '/usr/share/namban/oldconffiles/resolved.conf': No such file or directory
Traceback (most recent call last):
  File "/usr/lib/namban/src/view/__init__.py", line 30, in onChange
    self.app.connectProfile(self.domain)
  File "/usr/lib/namban/src/control.py", line 27, in connectProfile
    self.systemDnsSet(profile)
  File "/usr/lib/namban/src/core/__init__.py", line 9, in systemDnsSet
    self.currentStrategy.connect()
  File "/usr/lib/namban/src/core/strategy.py", line 55, in connect
    resolvdPromise((settings.APP_FILES_PATH/'oldconffiles/resolved.conf').__str__())
  File "/usr/lib/namban/src/core/promises.py", line 6, in __init__
    super().__init__(path=path,**d)
  File "/usr/lib/namban/src/core/basePromise.py", line 12, in __init__
    f = open(fp, "w+")
        ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/namban/promises/4a606591b527d6e505b1476ab305553d3ae9ac0d556726cec93a6af8804fe7e4.promise'

```

I clicked on the shecan dns to turn it on, this error appeared. The dns was not set.

**Comment by meshya** [comment]
Fixed in [v0.3-1](https://github.com/parchlinuxB/namban/releases/tag/v0.3-1)
If you see this bug 🐛 again, open a new issue
